# yaml-language-server: $schema=https://raw.githubusercontent.com/brigadecore/brigade/v2/v2/apiserver/schemas/project.json
apiVersion: brigade.sh/v2-alpha.5
kind: Project
metadata:
  id: kaniko
description: Brigade's Kaniko image built with Brigade 2!
spec:
  eventSubscriptions:
  - source: brigade.sh/github
    qualifiers:
      repo: brigadecore/kaniko
    types:
    - check_run:rerequested
    - check_suite:requested
    - check_suite:rerequested
    - push
  workerTemplate:
    git:
      cloneURL: https://github.com/brigadecore/kaniko.git
    jobPolicies:
      allowPrivileged: true
